channels:
    - conda-forge
dependencies:
    - python
    - pip
    - setuptools
    - matplotlib
    - jupyterlab
    - pip:
      - jupyterlab_latex
      - numpy
      - pandas
      - ipywidgets
      - jupyter_contrib_nbextensions
      - scipy
      - ipympl
